services:
  sam-server:
    image: ghcr.io/sam-research/sam-instant-messenger:main
    container_name: sam_server
    command: ["-i", "0.0.0.0"]
    environment:
      - RUST_LOG=info
    ports:
      - 8080:8080
  database:
    image: postgres:latest
    restart: always
    container_name: database_container
    depends_on:
      - sam-server
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
