networks:
  samnet:
    driver: bridge

services:
  sam_db:
    container_name: sam_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sam_db
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - samnet
  gateway:
    image: nginx:latest
    depends_on:
      - sam_db
      - sam_server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      - samnet
      - default
  sam_server:
    image: ghcr.io/sam-research/sam-instant-messenger:main
    depends_on:
      - sam_db
    container_name: sam_server
    command: ["-c", "config.json"]
    volumes:
      - ./sam.json:/config.json
    networks:
      - samnet
